import { API_ADVERTISER } from '.';
import { API_HOST } from './api_host.model';
import { API_LICENSE_PROPS } from './api_license.model';

export class API_DEALER {
    activeHost: string;
	advertisers: API_ADVERTISER[];
    businessName: string;
    city: string;
    contactNumber: string;
    contactPerson: string;
    contractDetails: string;
    createdBy: string;
    dateCreated: string;
    dateUpdated: string;
    dealerId: string;
    dealerIdAlias: string;
    dealer: any;
	dealerStats?: any;
    email?: string;
    forInstallationHost: number;
	generalCategory?: string;
    generatedId: string;
    hosts: API_HOST[];
    licenses: API_LICENSE_PROPS[];
    monthAsDealer: string;
    offlineLicenseCount?: number;
    onlineLicenseCount?: number;
    owner?: string;
    ownerFirstName?: string;
    ownerLastName?: string;
    region: string;
    startDate: string;
    state: string;
    status: string;
	tags: { dateCreated: string, name: string, ownerId: string, tagId: number, tagTypeId: number }[];
	totalAdvertisers: number;
    totalHost: string;
	totalOnlineLicense: number;
    updatedBy: string;
    userId: string;
}
