export interface API_FILTERS {
	active?: string;
	arrangement?: any;
	assigned?: any;
	daysInstalled?: any;
	daysOffline?: any;
	dealer?: string;
	dealer_id?: string;
	dealerId?: string;
	dmaRank?: number;
	dmaCode?: number;
	dmaName?: string;
	page?: number;
	filter?: string
	filterMin?: any;
	filterMax?: any;
    filterPerc?: any;
    filterPercMin?: any;
    filterPercMax?: any;
	hostId?: string;
	inactive?: any;
	installDate?: string;
	isActivated?: any;
	online?: any;
	pageSize?: any;
	piStatus?: string;
	role?: number;
	roleId?: string;
	search?: string;
	sortColumn?: string;
	status?: string;
	sortOrder?: string;
	timezone?: string;
	type?: any;
}
