import {
    BulkOptionsComponent,
    BulkPlaywhereComponent,
    ClonePlaylistComponent,
    ContentScheduleCardComponent,
    CreatePlaylistContentComponent,
    DeletePlaylistComponent,
    MediaPlaywhereComponent,
    OptionsComponent,
    PlayWhereComponent,
    PlaylistContentComponent,
    PlaylistContentPanelComponent,
    PlaylistContentSchedulingDialogComponent,
    PlaylistCreatedModalComponent,
    PlaylistDemoComponent,
    PlaylistEditModalComponent,
    PlaylistHostComponent,
    PlaylistInfoComponent,
    PlaylistMediaComponent,
    PlaylistMediaThumbnailComponent,
    PushUpdateComponent,
    ViewSchedulesComponent,
} from 'src/app/global/components_shared/playlist_components';

export const SHARED_PLAYLIST_COMPONENTS = [
    BulkOptionsComponent,
    BulkPlaywhereComponent,
    ClonePlaylistComponent,
    ContentScheduleCardComponent,
    CreatePlaylistContentComponent,
    DeletePlaylistComponent,
    MediaPlaywhereComponent,
    OptionsComponent,
    PlayWhereComponent,
    PlaylistContentComponent,
    PlaylistContentPanelComponent,
    PlaylistContentSchedulingDialogComponent,
    PlaylistCreatedModalComponent,
    PlaylistDemoComponent,
    PlaylistEditModalComponent,
    PlaylistHostComponent,
    PlaylistInfoComponent,
    PlaylistMediaComponent,
    PlaylistMediaThumbnailComponent,
    PushUpdateComponent,
    ViewSchedulesComponent,
];
