export const TIMEZONE_MAPPING = {
    'America/New_York': 'Eastern',
    'America/Chicago': 'Central',
    'America/Denver': 'Mountain',
    'America/Los_Angeles': 'Pacific',
    'America/Anchorage': 'Alaska',
    'Pacific/Honolulu': 'Hawaii',
    'America/Phoenix': 'Arizona',
    'America/Boise': 'Mountain',
    'America/Indiana/Indianapolis': 'Eastern',
    'America/Indiana/Knox': 'Central',
    'America/Indiana/Marengo': 'Eastern',
    'America/Indiana/Petersburg': 'Eastern',
    'America/Indiana/Tell_City': 'Central',
    'America/Indiana/Vevay': 'Eastern',
    'America/Indiana/Vincennes': 'Eastern',
    'America/Indiana/Winamac': 'Eastern',
    'America/Kentucky/Louisville': 'Eastern',
    'America/Kentucky/Monticello': 'Central',
    'America/Detroit': 'Eastern',
    'America/Menominee': 'Central',
    'America/North_Dakota/Beulah': 'Central',
    'America/North_Dakota/Center': 'Central',
    'America/North_Dakota/New_Salem': 'Central',
};
